import MainContainer from 'components/MainContainer/MainContainer'
import NavBarContainer from 'components/NavBarContainer/NavBarContainer'
import SuggestFollowContainer from 'components/SuggestFollowContainer/SuggestFollowContainer'